# Copyright (C) 2012-2016 The CyanogenMod Project
# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/smdk4412-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/smdk4412-common/proprietary/addon.d/audmodlib.sh:system/addon.d/audmodlib.sh \
    vendor/samsung/smdk4412-common/proprietary/addon.d/modid.sh:system/addon.d/modid.sh \
    vendor/samsung/smdk4412-common/proprietary/app/As/As.apk:system/app/As/As.apk \
    vendor/samsung/smdk4412-common/proprietary/app/AsUI/AsUI.apk:system/app/AsUI/AsUI.apk \
    vendor/samsung/smdk4412-common/proprietary/app/ViPER4AndroidFX/ViPER4AndroidFX.apk:system/app/ViPER4AndroidFX/ViPER4AndroidFX.apk \
    vendor/samsung/smdk4412-common/proprietary/bin/basimage_ibeats.bin:system/bin/basimage_ibeats.bin \
    vendor/samsung/smdk4412-common/proprietary/bin/basimage_ibeats.bin:system/bin/basimage_ibeats_solo.bin \
    vendor/samsung/smdk4412-common/proprietary/bin/basimage_ibeats.bin:system/bin/basimage_ibeats_solo_x.bin \
    vendor/samsung/smdk4412-common/proprietary/bin/basimage_ibeats.bin:system/bin/basimage_ibeats_x.bin \
    vendor/samsung/smdk4412-common/proprietary/bin/dynimage_ibeats.bin:system/bin/dynimage_ibeats.bin \
    vendor/samsung/smdk4412-common/proprietary/bin/dynimage_ibeats.bin:system/bin/dynimage_ibeats_solo.bin \
    vendor/samsung/smdk4412-common/proprietary/bin/dynimage_ibeats.bin:system/bin/dynimage_ibeats_solo_x.bin \
    vendor/samsung/smdk4412-common/proprietary/bin/dynimage_ibeats.bin:system/bin/dynimage_ibeats_x.bin \
    vendor/samsung/smdk4412-common/proprietary/bin/peqimage_ibeats.bin:system/bin/peqimage_ibeats.bin \
    vendor/samsung/smdk4412-common/proprietary/bin/peqimage_ibeats.bin:system/bin/peqimage_ibeats_solo.bin \
    vendor/samsung/smdk4412-common/proprietary/bin/peqimage_ibeats.bin:system/bin/peqimage_ibeats_solo_x.bin \
    vendor/samsung/smdk4412-common/proprietary/bin/peqimage_ibeats.bin:system/bin/peqimage_ibeats_x.bin \
    vendor/samsung/smdk4412-common/proprietary/bin/bcm4334.hcd:system/bin/bcm4334.hcd \
    vendor/samsung/smdk4412-common/proprietary/bin/bcm4334_murata.hcd:system/bin/bcm4334_murata.hcd \
    vendor/samsung/smdk4412-common/proprietary/bin/bcm4334_semco.hcd:system/bin/bcm4334_semco.hcd \
    vendor/samsung/smdk4412-common/proprietary/bin/bcm4334_semcosh.hcd:system/bin/bcm4334_semcosh.hcd \
    vendor/samsung/smdk4412-common/proprietary/bin/cbd:system/bin/cbd \
    vendor/samsung/smdk4412-common/proprietary/bin/gps.cer:system/bin/gps.cer \
    vendor/samsung/smdk4412-common/proprietary/cameradata/datapattern_420sp.yuv:system/cameradata/datapattern_420sp.yuv \
    vendor/samsung/smdk4412-common/proprietary/cameradata/datapattern_front_420sp.yuv:system/cameradata/datapattern_front_420sp.yuv \
    vendor/samsung/smdk4412-common/proprietary/etc/srm.bin:system/etc/srm.bin \
    vendor/samsung/smdk4412-common/proprietary/etc/AudioBTID.csv:system/etc/AudioBTID.csv \
    vendor/samsung/smdk4412-common/proprietary/etc/AudioFilter.csv:system/etc/AudioFilter.csv \
    vendor/samsung/smdk4412-common/proprietary/etc/AudioFilterPlatform.csv:system/etc/AudioFilterPlatform.csv \
    vendor/samsung/smdk4412-common/proprietary/etc/AudioFilterProduct.csv:system/etc/AudioFilterProduct.csv \
    vendor/samsung/smdk4412-common/proprietary/etc/AutoVolumeControl.txt:system/etc/AutoVolumeControl.txt \
    vendor/samsung/smdk4412-common/proprietary/etc/eqfilter.txt:system/etc/eqfilter.txt \
    vendor/samsung/smdk4412-common/proprietary/etc/HP_Audio.csv:system/etc/HP_Audio.csv \
    vendor/samsung/smdk4412-common/proprietary/etc/HP_Video.csv:system/etc/HP_Video.csv \
    vendor/samsung/smdk4412-common/proprietary/etc/pvplayer.cfg:system/etc/pvplayer.cfg \
    vendor/samsung/smdk4412-common/proprietary/etc/soundbooster.txt:system/etc/soundbooster.txt \
    vendor/samsung/smdk4412-common/proprietary/etc/audio/aeqcoe.txt:system/etc/audio/aeqcoe.txt \
    vendor/samsung/smdk4412-common/proprietary/etc/audio/eqfilter.txt:system/etc/audio/eqfilter.txt \
    vendor/samsung/smdk4412-common/proprietary/etc/audio/lmfilter.txt:system/etc/audio/lmfilter.txt \
    vendor/samsung/smdk4412-common/proprietary/etc/audio/situation.txt:system/etc/audio/situation.txt \
    vendor/samsung/smdk4412-common/proprietary/etc/audio/soundbooster.txt:system/etc/audio/soundbooster.txt \
    vendor/samsung/smdk4412-common/proprietary/etc/audio/stream_earpiece.txt:system/etc/audio/stream_earpiece.txt \
    vendor/samsung/smdk4412-common/proprietary/etc/audio/stream_headset.txt:system/etc/audio/stream_headset.txt \
    vendor/samsung/smdk4412-common/proprietary/etc/audio/stream_speaker.txt:system/etc/audio/stream_speaker.txt \
    vendor/samsung/smdk4412-common/proprietary/etc/dolby/ds-default.xml:system/etc/dolby/ds-default.xml \
    vendor/samsung/smdk4412-common/proprietary/etc/wifi/bcmdhd_apsta.bin_b2:system/etc/wifi/bcmdhd_apsta.bin_b2 \
    vendor/samsung/smdk4412-common/proprietary/etc/wifi/bcmdhd_mfg.bin_b2:system/etc/wifi/bcmdhd_mfg.bin_b2 \
    vendor/samsung/smdk4412-common/proprietary/etc/wifi/bcmdhd_p2p.bin_b2:system/etc/wifi/bcmdhd_p2p.bin_b2 \
    vendor/samsung/smdk4412-common/proprietary/etc/wifi/bcmdhd_sta.bin_b2:system/etc/wifi/bcmdhd_sta.bin_b2 \
    vendor/samsung/smdk4412-common/proprietary/etc/wifi/nvram_mfg.txt:system/etc/wifi/nvram_mfg.txt \
    vendor/samsung/smdk4412-common/proprietary/etc/wifi/nvram_mfg.txt_murata:system/etc/wifi/nvram_mfg.txt_murata \
    vendor/samsung/smdk4412-common/proprietary/etc/wifi/nvram_mfg.txt_semcosh:system/etc/wifi/nvram_mfg.txt_semcosh \
    vendor/samsung/smdk4412-common/proprietary/etc/wifi/nvram_net.txt:system/etc/wifi/nvram_net.txt \
    vendor/samsung/smdk4412-common/proprietary/etc/wifi/nvram_net.txt_murata:system/etc/wifi/nvram_net.txt_murata \
    vendor/samsung/smdk4412-common/proprietary/etc/wifi/nvram_net.txt_semcosh:system/etc/wifi/nvram_net.txt_semcosh \
    vendor/samsung/smdk4412-common/proprietary/lib/egl/libGLESv1_CM_mali.so:system/lib/egl/libGLESv1_CM_mali.so \
    vendor/samsung/smdk4412-common/proprietary/lib/egl/libGLESv2_mali.so:system/lib/egl/libGLESv2_mali.so \
    vendor/samsung/smdk4412-common/prebuilt/libMali/lib/libMali.so:obj/lib/libMali.so \
    vendor/samsung/smdk4412-common/proprietary/lib/libMcClient.so:system/lib/libMcClient.so \
    vendor/samsung/smdk4412-common/proprietary/lib/libMcRegistry.so:system/lib/libMcRegistry.so \
    vendor/samsung/smdk4412-common/proprietary/lib/libMcVersion.so:system/lib/libMcVersion.so \
    vendor/samsung/smdk4412-common/proprietary/lib/libcec.so:system/lib/libcec.so \
    vendor/samsung/smdk4412-common/proprietary/lib/libddc.so:system/lib/libddc.so \
    vendor/samsung/smdk4412-common/proprietary/lib/libedid.so:system/lib/libedid.so \
    vendor/samsung/smdk4412-common/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/smdk4412-common/proprietary/lib/libbass.so:system/lib/libbass.so \
    vendor/samsung/smdk4412-common/proprietary/lib/libbass_aac.so:system/lib/libbass_aac.so \
    vendor/samsung/smdk4412-common/proprietary/lib/libbass_alac.so:system/lib/libbass_alac.so \
    vendor/samsung/smdk4412-common/proprietary/lib/libbassdsd.so:system/lib/libbassdsd.so \
    vendor/samsung/smdk4412-common/proprietary/lib/libbassflac.so:system/lib/libbassflac.so \
    vendor/samsung/smdk4412-common/proprietary/lib/libbassmix.so:system/lib/libbassmix.so \
    vendor/samsung/smdk4412-common/proprietary/lib/libbeatsbass.so:system/lib/libbeatsbass.so \
    vendor/samsung/smdk4412-common/proprietary/lib/libbundlewrapper.so:system/lib/libbundlewrapper.so \
    vendor/samsung/smdk4412-common/proprietary/lib/libcyanogen-dsp.so:system/lib/libcyanogen-dsp.so \
    vendor/samsung/smdk4412-common/proprietary/lib/libdlpdapstorage.so:system/lib/libdlpdapstorage.so \
    vendor/samsung/smdk4412-common/proprietary/lib/libgnustl_shared.so:system/lib/libgnustl_shared.so \
    vendor/samsung/smdk4412-common/proprietary/lib/libLizticMetadataReader.so:system/lib/libLizticMetadataReader.so \
    vendor/samsung/smdk4412-common/proprietary/lib/libreverbwrapper.so:system/lib/libreverbwrapper.so \
    vendor/samsung/smdk4412-common/proprietary/lib/libspotify_embedded_shared.so:system/lib/libspotify_embedded_shared.so \
    vendor/samsung/smdk4412-common/proprietary/lib/libspotify_sdk.so:system/lib/libspotify_sdk.so \
    vendor/samsung/smdk4412-common/proprietary/lib/libsrsfx.so:system/lib/libsrsfx.so \
    vendor/samsung/smdk4412-common/proprietary/lib/libTinyAlsaMixer.so:system/lib/libTinyAlsaMixer.so \
    vendor/samsung/smdk4412-common/proprietary/lib/libv4a_fx_jb_ics.so:system/lib/libv4a_fx_jb_ics.so \
    vendor/samsung/smdk4412-common/proprietary/lib/libvisualizer.so:system/lib/libvisualizer.so \
    vendor/samsung/smdk4412-common/proprietary/lib/libxloudwrapper.so:system/lib/libxloudwrapper.so \
    vendor/samsung/smdk4412-common/proprietary/lib/soundfx/libswdap-mod.so:system/lib/soundfx/libswdap-mod.so \
    vendor/samsung/smdk4412-common/proprietary/usr/idc/melfas_ts.idc:system/usr/idc/melfas_ts.idc \
    vendor/samsung/smdk4412-common/proprietary/usr/idc/sec_touchscreen.idc:system/usr/idc/sec_touchscreen.idc \
    vendor/samsung/smdk4412-common/proprietary/usr/keylayout/gpio-keys.kl:system/usr/keylayout/gpio-keys.kl \
    vendor/samsung/smdk4412-common/proprietary/usr/keylayout/sii9234_rcp.kl:system/usr/keylayout/sii9234_rcp.kl \
    vendor/samsung/smdk4412-common/proprietary/vendor/firmware/SlimISP_BH.bin:system/vendor/firmware/SlimISP_BH.bin \
    vendor/samsung/smdk4412-common/proprietary/vendor/firmware/SlimISP_GD.bin:system/vendor/firmware/SlimISP_GD.bin \
    vendor/samsung/smdk4412-common/proprietary/vendor/firmware/SlimISP_GH.bin:system/vendor/firmware/SlimISP_GH.bin \
    vendor/samsung/smdk4412-common/proprietary/vendor/firmware/SlimISP_GK.bin:system/vendor/firmware/SlimISP_GK.bin \
    vendor/samsung/smdk4412-common/proprietary/vendor/firmware/SlimISP_JH.bin:system/vendor/firmware/SlimISP_JH.bin \
    vendor/samsung/smdk4412-common/proprietary/vendor/firmware/SlimISP_PH.bin:system/vendor/firmware/SlimISP_PH.bin \
    vendor/samsung/smdk4412-common/proprietary/vendor/firmware/SlimISP_WH.bin:system/vendor/firmware/SlimISP_WH.bin \
    vendor/samsung/smdk4412-common/proprietary/vendor/firmware/SlimISP_ZD.bin:system/vendor/firmware/SlimISP_ZD.bin \
    vendor/samsung/smdk4412-common/proprietary/vendor/firmware/SlimISP_ZH.bin:system/vendor/firmware/SlimISP_ZH.bin \
    vendor/samsung/smdk4412-common/proprietary/vendor/firmware/SlimISP_ZK.bin:system/vendor/firmware/SlimISP_ZK.bin \
    vendor/samsung/smdk4412-common/proprietary/vendor/firmware/SlimISP_ZM.bin:system/vendor/firmware/SlimISP_ZM.bin \
    vendor/samsung/smdk4412-common/proprietary/vendor/firmware/fimc_is_fw.bin:system/vendor/firmware/fimc_is_fw.bin \
    vendor/samsung/smdk4412-common/proprietary/vendor/firmware/mfc_fw.bin:system/vendor/firmware/mfc_fw.bin \
    vendor/samsung/smdk4412-common/proprietary/vendor/firmware/setfile.bin:system/vendor/firmware/setfile.bin \
    vendor/samsung/smdk4412-common/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so
